name: Apple Stock Bot

on:
  schedule:
    # Singapore (UTC+8): 8am, 9am, 10am, 1pm, 2pm, 3pm
    - cron: "0 0,1,2,5,6,7 * * *"  # UTC times
  workflow_dispatch:  # allow manual trigger

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py
